# Nombre de la aplicación
spring.application.name=digital-wallet-refunds

# Configuración del servidor (Netty)
server.port=8080

# Configuración del conector reactivo R2DBC a PostgreSQL
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/digital_wallet_db
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Pool de conexiones R2DBC
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=10

# Configuración del esquema por defecto (public)
spring.r2dbc.properties.schema=public

# Mostrar logs de consultas SQL (útil para depuración)
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql=DEBUG

# Exposición de endpoints de Actuator
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Configuración de OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Integración Inter-Servicios (WebClient)
persistence.service.url=${PERSISTENCE_SERVICE_URL:http://localhost:8081}
logging.level.com.digitalwallet.refunds=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

# -------------------------------------------------------------
# Configuración del Circuit Breaker (Resilience4j)
# -------------------------------------------------------------
resilience4j.circuitbreaker.instances.persistenceServiceCB.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.persistenceServiceCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.persistenceServiceCB.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.persistenceServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.persistenceServiceCB.waitDurationInOpenState=10000ms
resilience4j.circuitbreaker.instances.persistenceServiceCB.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.persistenceServiceCB.automaticTransitionFromOpenToHalfOpenEnabled=true

# -------------------------------------------------------------
# Configuración del TimeLimiter (Timeout)
# -------------------------------------------------------------
resilience4j.timelimiter.instances.persistenceServiceCB.timeoutDuration=2s
# Inicialización automática del esquema con R2DBC
spring.r2dbc.initialization-mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.mode=never