# Nombre de la aplicación
spring.application.name=digital-wallet-refunds

# Configuración del servidor (Netty)
server.port=8080

# Configuración del conector reactivo R2DBC a PostgreSQL
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/digital_wallet_db
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Pool de conexiones R2DBC
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=10

# Configuración del esquema por defecto (public)
spring.r2dbc.properties.schema=public

# Mostrar logs de consultas SQL (útil para depuración)
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql=DEBUG

# Exposición de endpoints de Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Configuración de OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method